
-- Create pending_notifications table
CREATE TABLE IF NOT EXISTS "public"."pending_notifications" (
    "id" bigint generated by default as identity not null PRIMARY KEY,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "phone" text not null,
    "title" text not null,
    "body" text not null,
    "booking_id" bigint references "public"."bookings"("id") on delete cascade,
    "status" text default 'pending'
);

ALTER TABLE "public"."pending_notifications" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for service_role" ON "public"."pending_notifications"
AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Trigger Function for Booking Updates
CREATE OR REPLACE FUNCTION "public"."handle_booking_notification"()
RETURNS TRIGGER AS $$
BEGIN
  -- Call Edge Function
  PERFORM net.http_post(
    'https://tikqxpgqgfciuyvaspdi.supabase.co/functions/v1/telegram-bot?type=booking_update',
    jsonb_build_object('record', NEW),
    '{"Content-Type": "application/json", "Authorization": "Bearer "}' -- Bearer token usually needed? Trigger usually runs as postgres or we need to hardcode service key or use supabase_functions.http_request if available
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger Function for Device Registration
CREATE OR REPLACE FUNCTION "public"."handle_device_registration"()
RETURNS TRIGGER AS $$
BEGIN
  -- Call Edge Function
  PERFORM net.http_post(
    'https://tikqxpgqgfciuyvaspdi.supabase.co/functions/v1/telegram-bot?type=device_register',
    jsonb_build_object('record', NEW),
    '{"Content-Type": "application/json", "Authorization": "Bearer "}'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Note: The http_request call above assumes 'net' extension or similar. 
-- The existing migration used `supabase_functions.http_request`. I should match that.

-- Correct Trigger Function using supabase_functions.http_request
CREATE OR REPLACE FUNCTION "public"."trigger_booking_notification"()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM supabase_functions.http_request(
      'https://tikqxpgqgfciuyvaspdi.supabase.co/functions/v1/telegram-bot',
      'POST',
      '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpa3F4cGdxZ2ZjaXV5dmFzcGRpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTU4MDg4NCwiZXhwIjoyMDgxMTU2ODg0fQ.__5WIk8UWGWszjUaTSRrcwdT_c4YSOKJILHN6eXIJbs"}',
      jsonb_build_object('type', 'booking_update', 'record', NEW)::text,
      '5000'
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION "public"."trigger_device_registration"()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM supabase_functions.http_request(
      'https://tikqxpgqgfciuyvaspdi.supabase.co/functions/v1/telegram-bot',
      'POST',
      '{"Content-type":"application/json","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpa3F4cGdxZ2ZjaXV5dmFzcGRpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTU4MDg4NCwiZXhwIjoyMDgxMTU2ODg0fQ.__5WIk8UWGWszjUaTSRrcwdT_c4YSOKJILHN6eXIJbs"}',
      jsonb_build_object('type', 'device_register', 'record', NEW)::text,
      '5000'
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers
DROP TRIGGER IF EXISTS "notify-booking-update" ON "public"."bookings";
CREATE TRIGGER "notify-booking-update"
AFTER INSERT OR UPDATE ON "public"."bookings"
FOR EACH ROW
EXECUTE FUNCTION "public"."trigger_booking_notification"();

DROP TRIGGER IF EXISTS "notify-device-register" ON "public"."team_devices";
CREATE TRIGGER "notify-device-register"
AFTER INSERT ON "public"."team_devices"
FOR EACH ROW
EXECUTE FUNCTION "public"."trigger_device_registration"();
