create table public.team_devices (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  name text not null,
  push_token text not null,
  last_active timestamp with time zone null default now(),
  phone text null,
  constraint team_devices_pkey primary key (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists team_devices_token_idx on public.team_devices using btree (push_token) TABLESPACE pg_default;
