
-- Enable pg_net extension for HTTP requests
CREATE EXTENSION IF NOT EXISTS "pg_net";

-- Create pending_notifications table
CREATE TABLE IF NOT EXISTS "public"."pending_notifications" (
    "id" bigint generated by default as identity not null PRIMARY KEY,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "phone" text not null,
    "title" text not null,
    "body" text not null,
    "booking_id" bigint references "public"."bookings"("id") on delete cascade,
    "status" text default 'pending'
);

ALTER TABLE "public"."pending_notifications" ENABLE ROW LEVEL SECURITY;

-- Drop policy if exists to allow re-running migration
DROP POLICY IF EXISTS "Enable all for service_role" ON "public"."pending_notifications";

CREATE POLICY "Enable all for service_role" ON "public"."pending_notifications"
AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Trigger Function for Booking Updates
CREATE OR REPLACE FUNCTION "public"."trigger_booking_notification"()
RETURNS TRIGGER AS $$
DECLARE
  request_id bigint;
BEGIN
    -- Use net.http_post with named parameters to avoid signature mismatch
    PERFORM net.http_post(
      url := 'https://tikqxpgqgfciuyvaspdi.supabase.co/functions/v1/telegram-bot?type=booking_update',
      body := jsonb_build_object('record', NEW),
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpa3F4cGdxZ2ZjaXV5dmFzcGRpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTU4MDg4NCwiZXhwIjoyMDgxMTU2ODg0fQ.__5WIk8UWGWszjUaTSRrcwdT_c4YSOKJILHN6eXIJbs'
      )
    );
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger Function for Device Registration
CREATE OR REPLACE FUNCTION "public"."trigger_device_registration"()
RETURNS TRIGGER AS $$
DECLARE
  request_id bigint;
BEGIN
    PERFORM net.http_post(
      url := 'https://tikqxpgqgfciuyvaspdi.supabase.co/functions/v1/telegram-bot?type=device_register',
      body := jsonb_build_object('record', NEW),
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpa3F4cGdxZ2ZjaXV5dmFzcGRpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NTU4MDg4NCwiZXhwIjoyMDgxMTU2ODg0fQ.__5WIk8UWGWszjUaTSRrcwdT_c4YSOKJILHN6eXIJbs'
      )
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Triggers
DROP TRIGGER IF EXISTS "notify-booking-update" ON "public"."bookings";
CREATE TRIGGER "notify-booking-update"
AFTER INSERT OR UPDATE ON "public"."bookings"
FOR EACH ROW
EXECUTE FUNCTION "public"."trigger_booking_notification"();

DROP TRIGGER IF EXISTS "notify-device-register" ON "public"."team_devices";
CREATE TRIGGER "notify-device-register"
AFTER INSERT ON "public"."team_devices"
FOR EACH ROW
EXECUTE FUNCTION "public"."trigger_device_registration"();
